language: node_js
node_js:
- 6.12.2
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - DEPLOY_BRANCH=master
  - STAGING_BRANCH=staging
cache:
  directories:
  - node_modules
  - bundle/cache
before_install:
- openssl aes-256-cbc -K $encrypted_eb7688b5aa49_key -iv $encrypted_eb7688b5aa49_iv -in rdr2018.enc -out rdr2018 -d
- chmod 400 rdr2018
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/build.sh
script:
- "./.build_scripts/build.sh"
after_success:
- "./.build_scripts/deploy.sh"
