language: node_js
node_js:
- 6.12.2
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - DEPLOY_BRANCH=master
  - BLUEHOST_USER=ranking5
  - BLUEHOST_PATH=rankingdigitalrights.org:public_html/index2018
cache:
  directories:
  - node_modules
  - bundle/cache
before_install:
- openssl aes-256-cbc -K $encrypted_487b6f3d6c7c_key -iv $encrypted_487b6f3d6c7c_iv
  -in rdr2018.enc -out rdr2018 -d
- chmod 400 rdr2018
- chmod +x ./.build_scripts/deploy.sh
- chmod +x ./.build_scripts/build.sh
script:
- "./.build_scripts/build.sh"
after_success:
- "./.build_scripts/deploy.sh"
