#!/usr/bin/env python3
from csv_json_converters.overview_json_converter import convert_overview_type_csv_to_json
from csv_json_converters.multiple_services_json_converter import convert_multiple_services_type_csv_to_json
from csv_json_converters.indicator_overview_json_converter import convert_scores_overview_type_csv_to_indicator_overview_json

if __name__ == '__main__':
    quick_overview_csv_location = '/home/filip/Downloads/RDRindex2017data/RDR2017 - Quick overview.csv'
    services_list_csv_location = '/home/filip/Downloads/Companies and services list 2017 - Services.csv'
    scores_overview_csv_location = '/home/filip/Downloads/RDRindex2017data - Scores overview.csv'
    output_directory = '/home/filip/workspace/rdr-2018/output/'

    convert_overview_type_csv_to_json(quick_overview_csv_location, output_directory)
    convert_multiple_services_type_csv_to_json(services_list_csv_location, output_directory)
    convert_scores_overview_type_csv_to_indicator_overview_json(scores_overview_csv_location, output_directory)
